# This is a development helper so we don't need to constantly
# manage all the moving parts with long docker commands
# To build this image, run `$ docker-compose build`
# To run this image locally, run `$ docker-compose up`
version: '3.7'
services:
  wordpress:
    image: steadypay/wordpress:4.9.7
    volumes:
      - ./wp-content:/var/www/public/blog/wp-content
      - ./secrets:/etc/secrets
    env_file: .env
    dns: 8.8.8.8
    ports:
      - "80:80"
    links:
      - mysql

  mysql:
    image: mariadb:10.1.22
    volumes:
      - ./mysql:/var/lib/mysql
      # Comment out next line if you don't want to import an existing database.
      # Should be used on first run only.
      # - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
